# permissions for end users to view tenantnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tenant-namespace-operator
    app.kubernetes.io/managed-by: kustomize
  name: tenantnamespace-viewer-role
rules:
- apiGroups:
  - miscscripts.pnnl.gov
  resources:
  - tenantnamespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - miscscripts.pnnl.gov
  resources:
  - tenantnamespaces/status
  verbs:
  - get
