# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gitlab-runner-operator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build gitlab-runner-operator container
      run: ./containers/build gitlab-runner-operator
