apiVersion: miscscripts.pnnl.gov/v1beta1
kind: TenantNamespace
metadata:
  labels:
    app.kubernetes.io/name: tenantnamespace
    app.kubernetes.io/instance: example
    app.kubernetes.io/part-of: tenant-namespace-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: tenant-namespace-operator
  name: example
spec:
  flavorRef:
    name: example
    kind: TenantNamespaceFlavor
    group: miscscripts.pnnl.gov
#  ingress:
#    nginx:
#      enabled: false
